import type { GameSession } from "@/lib/types";

const today = new Date();
const day = (daysAgo: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() - daysAgo);
  return d.toISOString();
};

const sessionTime = (daysAgo: number, hour: number, minute: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() - daysAgo);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
};

export const demoGameSessions: GameSession[] = [
  // Today
  {
    id: "session-001",
    patientId: "patient-001",
    gameId: "routine-ordering",
    difficulty: 2,
    score: 86,
    accuracy: 90,
    attempts: 5,
    responseTime: 8200,
    hintsUsed: 1,
    completed: true,
    abandoned: false,
    startedAt: sessionTime(0, 10, 32),
    completedAt: sessionTime(0, 10, 45),
  },
  {
    id: "session-002",
    patientId: "patient-001",
    gameId: "hide-object",
    difficulty: 2,
    score: 78,
    accuracy: 80,
    attempts: 4,
    responseTime: 11400,
    hintsUsed: 2,
    completed: true,
    abandoned: false,
    startedAt: sessionTime(0, 11, 5),
    completedAt: sessionTime(0, 11, 20),
  },
  {
    id: "session-003",
    patientId: "patient-001",
    gameId: "family-memory",
    difficulty: 1,
    score: 92,
    accuracy: 95,
    attempts: 3,
    responseTime: 6800,
    hintsUsed: 0,
    completed: true,
    abandoned: false,
    startedAt: sessionTime(0, 12, 15),
    completedAt: sessionTime(0, 12, 25),
  },
  // Yesterday
  {
    id: "session-004",
    patientId: "patient-001",
    gameId: "routine-ordering",
    difficulty: 2,
    score: 80,
    accuracy: 85,
    attempts: 6,
    responseTime: 9100,
    hintsUsed: 1,
    completed: true,
    abandoned: false,
    startedAt: sessionTime(1, 9, 30),
    completedAt: sessionTime(1, 9, 45),
  },
  {
    id: "session-005",
    patientId: "patient-001",
    gameId: "hide-object",
    difficulty: 2,
    score: 72,
    accuracy: 75,
    attempts: 5,
    responseTime: 12300,
    hintsUsed: 2,
    completed: true,
    abandoned: false,
    startedAt: sessionTime(1, 10, 15),
    completedAt: sessionTime(1, 10, 30),
  },
  // 2 days ago
  {
    id: "session-006",
    patientId: "patient-001",
    gameId: "family-memory",
    difficulty: 1,
    score: 88,
    accuracy: 90,
    attempts: 3,
    responseTime: 7200,
    hintsUsed: 0,
    completed: true,
    abandoned: false,
    startedAt: sessionTime(2, 11, 0),
    completedAt: sessionTime(2, 11, 12),
  },
  {
    id: "session-007",
    patientId: "patient-001",
    gameId: "routine-ordering",
    difficulty: 1,
    score: 75,
    accuracy: 78,
    attempts: 7,
    responseTime: 10500,
    hintsUsed: 2,
    completed: true,
    abandoned: false,
    startedAt: sessionTime(2, 14, 0),
    completedAt: sessionTime(2, 14, 18),
  },
  // 3 days ago
  {
    id: "session-008",
    patientId: "patient-001",
    gameId: "hide-object",
    difficulty: 1,
    score: 68,
    accuracy: 70,
    attempts: 6,
    responseTime: 13100,
    hintsUsed: 3,
    completed: true,
    abandoned: false,
    startedAt: sessionTime(3, 10, 0),
    completedAt: sessionTime(3, 10, 20),
  },
  // 4 days ago
  {
    id: "session-009",
    patientId: "patient-001",
    gameId: "routine-ordering",
    difficulty: 1,
    score: 70,
    accuracy: 72,
    attempts: 8,
    responseTime: 11200,
    hintsUsed: 3,
    completed: true,
    abandoned: false,
    startedAt: sessionTime(4, 9, 45),
    completedAt: sessionTime(4, 10, 5),
  },
  {
    id: "session-010",
    patientId: "patient-001",
    gameId: "family-memory",
    difficulty: 1,
    score: 85,
    accuracy: 88,
    attempts: 4,
    responseTime: 7800,
    hintsUsed: 0,
    completed: true,
    abandoned: false,
    startedAt: sessionTime(4, 11, 30),
    completedAt: sessionTime(4, 11, 40),
  },
  // 5 days ago
  {
    id: "session-011",
    patientId: "patient-001",
    gameId: "hide-object",
    difficulty: 1,
    score: 65,
    accuracy: 68,
    attempts: 7,
    responseTime: 14000,
    hintsUsed: 3,
    completed: true,
    abandoned: false,
    startedAt: sessionTime(5, 10, 0),
    completedAt: sessionTime(5, 10, 22),
  },
  // 6 days ago
  {
    id: "session-012",
    patientId: "patient-001",
    gameId: "routine-ordering",
    difficulty: 1,
    score: 62,
    accuracy: 65,
    attempts: 9,
    responseTime: 12800,
    hintsUsed: 4,
    completed: true,
    abandoned: false,
    startedAt: sessionTime(6, 9, 30),
    completedAt: sessionTime(6, 9, 52),
  },
];
