import type { Routine } from "@/lib/types";

export const demoRoutines: Routine[] = [
  {
    id: "routine-001",
    patientId: "patient-001",
    label: "Wake Up",
    emoji: "🌅",
    description: "Wake up and stretch gently",
    location: "Bedroom",
    timeOfDay: "7:00 AM",
    stepOrder: 1,
    order: 1,
  },
  {
    id: "routine-002",
    patientId: "patient-001",
    label: "Brush Teeth",
    emoji: "🪥",
    description: "Brush teeth and freshen up",
    location: "Bathroom",
    timeOfDay: "7:15 AM",
    stepOrder: 2,
    order: 2,
  },
  {
    id: "routine-003",
    patientId: "patient-001",
    label: "Morning Prayer",
    emoji: "🙏",
    description: "Quiet morning prayer time",
    location: "Prayer Room",
    timeOfDay: "7:30 AM",
    stepOrder: 3,
    order: 3,
  },
  {
    id: "routine-004",
    patientId: "patient-001",
    label: "Breakfast",
    emoji: "🍽️",
    description: "Have a healthy breakfast",
    location: "Dining Room",
    timeOfDay: "8:00 AM",
    stepOrder: 4,
    order: 4,
  },
  {
    id: "routine-005",
    patientId: "patient-001",
    label: "Medicine",
    emoji: "💊",
    description: "Take blood pressure medicine",
    location: "Kitchen",
    timeOfDay: "10:00 AM",
    stepOrder: 5,
    order: 5,
  },
  {
    id: "routine-006",
    patientId: "patient-001",
    label: "Evening Walk",
    emoji: "🚶",
    description: "Go for a gentle evening walk",
    location: "Garden",
    timeOfDay: "5:00 PM",
    stepOrder: 6,
    order: 6,
  },
];
